input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
model_params_path: "configs/knn_config.yaml"
splitting_params:
  test_size: 0.2
  random_state: 42
train_params:
  model_type: "knn"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "fbs"
    - "slope"
    - "ca"
    - "thal"
    - "condition"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "oldpeak"
    - "thalach"
  features_to_drop:
    - ""
  target_col: "condition"