# CONSTANTS
dataset_name: "cherngs/heart-disease-cleveland-uci"

# PATH
raw_data_path: "data/raw"
interim_data_path: "data/interim"
predictions_data_path: "data/predictions/predictions.csv"
metrics_data_path: "metrics/metrics.json"

input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.joblib"
model_params_path: "configs/random_forest_config.yaml" # change this to any other available model if you want

# MODELS
splitting_params:
  test_size: 0.2
  random_state: 42
train_params:
  model_type: "random_forest"

# FEATURE ENGINEERING
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "fbs"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "oldpeak"
    - "thalach"
  target_col: "condition"